Leonardo/posts module improvements
desmos-labs/desmos pull request #397
Opened 2021-04-19 16:06 UTC by bragaz

## Description
This PR introduce some improvements to the `x/posts` module such as a renewed `disable-comments` flag and a new parameter to check the length of the `optionalData` `key` field.
Close #386.
Close #393.

## Checklist
- [ ] Targeted PR against correct branch.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit tests.
- [ ] Wrote integration tests (simulation & CLI). 
- [ ] Updated the documentation. 
- [ ] Added an entry to the `CHANGELOG.md` file.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

2021-04-29 05:16 UTC, RiccardoM requested changes
There are some simulation tests failing. Can you please fix those? Maybe a `master` pull will be sufficient

2021-05-14 07:47 UTC, RiccardoM commented on x/staging/posts/client/cli/tx.go
> +Comments to the post could be locked by including the --disable-comments flag.
```suggestion
Comments to the post can be disabled by including the --disable-comments flag.
```

2021-05-14 07:47 UTC, RiccardoM commented on x/staging/posts/client/cli/tx.go
> +   --disable-comments true
```suggestion
   --disable-comments
```

2021-05-14 07:47 UTC, RiccardoM commented on docs/developers/queries/staging/posts.md
> +# desmos query posts --parent-id=a4469741bb0c0622627810082a5f2e4e54fbbb888f25a4771a5eebc697d30cfc --disable-comments=false --subspace=desmos --sort=created --sort-order=descending
```suggestion
# desmos query posts --parent-id=a4469741bb0c0622627810082a5f2e4e54fbbb888f25a4771a5eebc697d30cfc --subspace=desmos --sort=created --sort-order=descending
```

2021-05-14 07:47 UTC, RiccardoM approved these changes

2021-05-14 07:48 UTC, RiccardoM commented
@bragaz Can you please add two CHANGELOG entries for the edits you've made? You can add them to the `Unreleased` section of the change log

2021-05-14 07:52 UTC, bragaz commented
@RiccardoM I'm also solving #419 for this, I'll update it once done

2021-05-14 07:57 UTC, RiccardoM commented
@bragaz Please use the following conventions for variables: 

- `postID` instead of `postId` 
- `parentID` instead of `parentId` 

This should make us respect the language conventions as well

2021-05-14 09:44 UTC, RiccardoM commented on CHANGELOG.md
> +# Version 0.16.3
```suggestion
# Unreleased
```

2021-05-14 09:44 UTC, RiccardoM commented on CHANGELOG.md
> +- Capped the `optionalDataEntry` `key` field length ([#393](https://github.com/desmos-labs/desmos/issues/393)])
```suggestion
- Capped the `OptionalDataEntry.Key` length ([#393](https://github.com/desmos-labs/desmos/issues/393)])
```

2021-05-14 09:44 UTC, RiccardoM commented on CHANGELOG.md
> +
```suggestion
- Capped the `OptionalDataEntry.Key` length ([#393](https://github.com/desmos-labs/desmos/issues/393)])
- Removed `--allows-comments` in favor of `--disable-comments` ([#386](https://github.com/desmos-labs/desmos/issues/386))

```

2021-05-14 09:45 UTC, RiccardoM approved these changes

2021-05-14 09:45 UTC, merged