Apple/user block pagination
desmos-labs/desmos pull request #506
Opened 2021-06-21 12:44 UTC by HarleyAppleChoi

## Description
Implenment pagination for user block
close #495 
## Checklist
- [ ] Targeted PR against correct branch.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit tests.
- [ ] Wrote integration tests (simulation & CLI). 
- [ ] Updated the documentation. 
- [ ] Added an entry to the `CHANGELOG.md` file.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

2021-06-23 05:29 UTC, RiccardoM reviewed
There seem to be a lot of build errors. Do you mind fixing those please? 
You can build the project running `make build` and then test it with `make test-unit`

2021-06-23 13:18 UTC, bragaz commented
@HarleyAppleChoi 
There are still some build errors plus the files are not properly formatted.
After you've fixed build errors try to run `make lint` it will show what the problems are

2021-06-23 13:19 UTC, bragaz requested changes
@HarleyAppleChoi
There are still some build errors plus the files are not properly formatted.
After you've fixed build errors try to run make lint it will show what the problems are

2021-06-23 16:03 UTC, bragaz commented
I see from the failing coverage's checks that tests related to `userBlocks` for GRPC query, keeper and alias functions are missing. Can you add some tests for them? There are other similar tests in the `profiles` folder. You can take them as an example

2021-06-24 09:09 UTC, bragaz requested changes

2021-06-24 09:09 UTC, bragaz commented on x/profiles/keeper/alias_functions.go
> +func (k Keeper) IterateBlockedUsersByUserSubSpace(ctx sdk.Context, user string, subspace string, fn func(index int64, blocks types.UserBlock) (stop bool)) {
This function is used only inside `GetUserBlockByBlockerSubspace` which should be removed since it's unused, so we can remove this as well I think

2021-06-24 14:31 UTC, bragaz requested changes

2021-06-24 14:31 UTC, bragaz commented on x/profiles/keeper/grpc_query.go
> +		var rel types.UserBlock
```suggestion
		var userBlock types.UserBlock
```

2021-06-24 14:31 UTC, bragaz commented on x/profiles/keeper/grpc_query.go
>  func (k Keeper) UserBlocks(ctx context.Context, request *types.QueryUserBlocksRequest) (*types.QueryUserBlocksResponse, error) {
Can you add a test for this please? Doing so would probably fix the coverage issues

2021-06-25 08:26 UTC, dadamu commented on x/profiles/client/cli/cli_relationships.go
> +	flags.AddPaginationFlagsToCmd(cmd, types.QueryUserRelationships)
The `types.QueryUserRelationships` is for creating the relationship. I think it should be `types.QueryUserBlocks`. If it is not present, we should add one in the `key.go`.

2021-06-25 08:27 UTC, RiccardoM commented on x/profiles/keeper/alias_functions.go
> +func (k Keeper) IterateBlockedUsers(ctx sdk.Context, user string, fn func(index int64, blocks types.UserBlock) (stop bool)) {
```suggestion
// IterateBlockedUsers iterates through the list of users blocked by the specified user and performs the given function
func (k Keeper) IterateBlockedUsers(ctx sdk.Context, user string, fn func(index int64, blocks types.UserBlock) (stop bool)) {
```

2021-06-25 08:27 UTC, RiccardoM commented on x/profiles/keeper/alias_functions.go
> +}
We can remove useless empty lines
```suggestion
	store := ctx.KVStore(k.storeKey)
	iterator := sdk.KVStorePrefixIterator(store, types.BlockerPrefix(user))
	defer iterator.Close()

	i := int64(0)
	for ; iterator.Valid(); iterator.Next() {
		block := types.MustUnmarshalUserBlock(k.cdc, iterator.Value())
		stop := fn(i, block)
		if stop {
			break
		}
		i++
	}
}
```

2021-06-25 08:27 UTC, RiccardoM commented on x/profiles/keeper/grpc_query.go
> +	// Get paginated user userBlockationships
```suggestion
	// Get paginated user blocks
```

2021-06-25 08:27 UTC, RiccardoM commented on x/profiles/keeper/grpc_query_test.go
> +			name: "query relationsips without pagination",
```suggestion
			name: "query blocks without pagination",
```

2021-06-25 08:27 UTC, RiccardoM commented on x/profiles/keeper/grpc_query_test.go
> +			name: "query relationsips with pagination",
```suggestion
			name: "query blocks with pagination",
```

2021-06-25 08:27 UTC, RiccardoM commented on x/profiles/keeper/keeper_blocks.go
> +// SaveUserBlock allows to store the given block in a specific subspace inside the store, returning an error if
```suggestion
// SaveUserBlock allows to store the given block inside the store, returning an error if
```

2021-06-25 08:27 UTC, RiccardoM commented on x/profiles/keeper/keeper_blocks.go
> +// DeleteUserBlock allows to the specified blocker in a specific subspace to unblock the given blocked user.
```suggestion
// DeleteUserBlock allows to the specified blocker to unblock the given blocked user.
```

2021-06-25 08:27 UTC, RiccardoM commented on x/profiles/keeper/keeper_blocks.go
> +	//Delete key directly since that is 1-to-1
```suggestion

```

2021-06-25 08:27 UTC, RiccardoM commented on x/profiles/types/keys.go
> +func BlockerPrefix(blocker string) []byte {
```suggestion
// BLockPrefix returns the store prefix used to store the blocks created by the given blocker
func BlockerPrefix(blocker string) []byte {
```

2021-06-25 08:27 UTC, RiccardoM commented on x/profiles/types/keys.go
> +func BlockerSubspacePrefix(blocker string, subspace string) []byte {
```suggestion
// BlockerSubspacePrefix returns the store prefix used to store the blocks that the given blocker has created inside the specified subspace
func BlockerSubspacePrefix(blocker string, subspace string) []byte {
```

2021-06-25 08:27 UTC, RiccardoM commented on x/profiles/types/keys.go
>  // UsersBlocksStoreKey turns a user address to a key used to store a Address -> []Address couple
```suggestion
// UsersBlocksStoreKey returns the store key used to save the block made by the given blocker, inside the specified subspace and towards the given blocked user
```

2021-06-25 08:27 UTC, RiccardoM commented on x/profiles/types/models_relationships.go
> +// the provided BinaryMarshaler
```suggestion
// MustUnmarshalUserBlock deserializes the given byte array as a UserBlock using the provided BinaryMarshaler
```

2021-06-25 08:28 UTC, dadamu commented on x/profiles/keeper/grpc_query_test.go
> +			name: "query relationsips without pagination",
```suggestion
			name: "query user blocklist without pagination",
```

2021-06-25 08:28 UTC, dadamu commented on x/profiles/keeper/grpc_query_test.go
> +			name: "query relationsips with pagination",
```suggestion
			name: "query user blocklist with pagination",
```

2021-06-28 05:09 UTC, RiccardoM commented on CHANGELOG.md
> +- Improved the blocklist query ([#495](https://github.com/desmos-labs/desmos/issues/495))
```suggestion
- Added the ability to paginate user blocks ([#495](https://github.com/desmos-labs/desmos/issues/495))
```

2021-06-28 05:09 UTC, RiccardoM approved these changes

2021-06-28 08:08 UTC, bragaz approved these changes

2021-06-28 08:08 UTC, merged