fix: Subspaces cli commands and proto files wrong notations
desmos-labs/desmos pull request #815
Opened 2022-04-11 08:23 UTC by bragaz

This PR aim to solve some minor issues that I've found inside the `x/subspaces` module.
1. Updates the `groups` CLI commands examples
2. Fixes wrong notations in `subspaces` models proto file
3. Add missing `GetCmdDeleteSubspace` to the `TxCmd`

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/desmos-labs/desmos/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://docs.cosmos.network/v0.44/building-modules/intro.html)
- [ ] included the necessary unit and integration [tests](https://github.com/desmos-labs/desmos/blob/master/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

2022-04-11 09:41 UTC, RiccardoM approved these changes

2022-04-11 09:45 UTC, RiccardoM requested changes
We need a changeset entry here

2022-04-11 10:25 UTC, RiccardoM requested changes

2022-04-11 10:25 UTC, RiccardoM commented on go.mod
> +	github.com/desmos-labs/changeset v0.0.0-20220321084648-83441159ab4f // indirect
This shouldn't be here

2022-04-11 10:25 UTC, RiccardoM commented on .changeset/entries/9823041f2fc00cbc264d66d2f4f7b02652004a1296489aa64b6b7b586d6329a5.yaml
> +description: fixed wrong proto files notations and added a missing cli command
```suggestion
description: Fixed wrong Proto files notations and missing CLI command
```

2022-04-11 11:12 UTC, bragaz commented
I found that `GetCmdQueryUserGroup()` was missing and added it

2022-04-11 11:33 UTC, dadamu commented on x/subspaces/client/cli/query.go
> +func GetCmdQueryUserGroup() *cobra.Command {
missing doc here.

2022-04-12 03:58 UTC, dadamu approved these changes

2022-04-12 03:59 UTC, merged