feat: add missing reports queries methods
desmos-labs/desmos pull request #930
Opened 2022-06-23 09:39 UTC by RiccardoM

## Description
This PR adds some missing queries methods for the `x/reports` module

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [x] targeted the correct branch (see [PR Targeting](https://github.com/desmos-labs/desmos/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [x] followed the guidelines for [building modules](https://docs.cosmos.network/v0.44/building-modules/intro.html)
- [x] included the necessary unit and integration [tests](https://github.com/desmos-labs/desmos/blob/master/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [x] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

2022-06-23 10:02 UTC, dadamu commented
@RiccardoM I thought the reason why these query methods are not in the ADR is they are unnecessary since no one would use the id to query a report or a reason.

2022-06-23 13:03 UTC, RiccardoM commented
> @RiccardoM I thought the reason why these query methods are not in the ADR is they are unnecessary since no one would use the id to query a report or a reason. What the reason you decide to add them?

While developing DJuno I discovered these kind of queries might come in handy for third-party tools

2022-06-24 05:49 UTC, dadamu approved these changes

2022-06-24 05:52 UTC, dadamu commented on proto/desmos/reports/v1/query.proto
> +        "/desmos/reports/v1/{subspace_id}/reports/{report_id}";
```suggestion
        "/desmos/reports/v1/subspaces/{subspace_id}/reports/{report_id}";
```

2022-06-24 05:52 UTC, dadamu commented on proto/desmos/reports/v1/query.proto
> +        "/desmos/reports/v1/{subspace_id}/reasons/{reason_id}";
```suggestion
        "/desmos/reports/v1/subspaces/{subspace_id}/reasons/{reason_id}";
```

2022-06-24 05:52 UTC, dadamu commented on proto/desmos/reports/v1/query.proto
>      option (google.api.http).get = "/desmos/reports/v1/{subspace_id}/reports";
```suggestion
    option (google.api.http).get = "/desmos/reports/v1/subspaces/{subspace_id}/reports";
```

2022-06-24 05:53 UTC, dadamu commented on proto/desmos/reports/v1/query.proto
>      option (google.api.http).get = "/desmos/reports/v1/{subspace_id}/reasons";
```suggestion
    option (google.api.http).get = "/desmos/reports/v1/subspaces/{subspace_id}/reasons";
```

2022-06-24 05:53 UTC, dadamu requested changes
We should follow the restful naming rule.

2022-06-24 07:52 UTC, dadamu approved these changes

2022-06-24 10:12 UTC, bragaz approved these changes

2022-06-24 10:29 UTC, merged